
#给lbs主机配置静态外网ip，网卡为：eth1
#- name: setup static ip address at "{{ eth1 }}"
#  template:
#    src: "{{ eth1 }}.j2"
#    dest: "/etc/sysconfig/network-scripts/ifcfg-{{ eth1 }}"
#    backup: yes
#  when: ( ansible_hostname is match (".*lbs.*") )

#1.关闭所有主机的firewalld防火墙
- name: Disabled Firewall Server
  systemd:
    name: firewalld
    state: stopped
    enabled: no

#开启manger组和lbs组主机的firewalld防火墙
- name: started manger group and lbs group hosts Firewall Server
  systemd:
    name: firewalld
    state: started
    enabled: yes
  when: ( ansible_hostname is match (".*manger.*") ) or  ( ansible_hostname is match (".*lbs.*") ) 
#2.关闭selinux
- name: Disabled Selinux Server
  selinux:
    state: disabled

###delete old yum repos
- name: mv  old-repo files
  shell: mv  /etc/yum.repos.d/* /tmp




#待优化yum源，解析到管理机下载源
#3.配置Base源、EPEL源
- name: Add Base EPEL repository
  yum_repository:
    name: "{{ item.name }}"
    description: "{{ item.description }}"
    baseurl: "{{ item.baseurl }}"
    gpgcheck: yes
    gpgkey: "{{ item.gpgkey }}"
  loop:
    - { name: base, description: Base repo , baseurl: 'http://mirrors.aliyun.com/centos/$releasever/os/$basearch', gpgkey: 'http://mirrors.aliyun.com/centos/RPM-GPG-KEY-CentOS-7' }
    - { name: epel, description: Epel repo , baseurl: 'http://mirrors.aliyun.com/epel/7/$basearch', gpgkey: 'https://mirrors.aliyun.com/epel/RPM-GPG-KEY-EPEL-7' }

#4.配置Nginx源、PHP-FPM源
- name: Add Nginx Repository
  yum_repository:
    name: nginx
    enabled: yes
    description: Nginx YUM repo
    baseurl: 'http://nginx.org/packages/centos/$releasever/$basearch/'
    gpgcheck: no
  when: ( ansible_hostname is match (".*lbs.*") ) or
        ( ansible_hostname is match (".*web.*") )

- name: Add PHP-FPM repository
  yum_repository:
    name: php-fpm
    description: PHP-FPM YUM repo
#    baseurl: http://us-east.repo.webtatic.com/yum/el7/x86_64/
    baseurl: http://192.168.199.191/yum/el7/x86_64/
#    baseurl: http://osker.ml/php-fpm/  #我的外网源
    gpgcheck: no
  when: ( ansible_hostname is match (".*phpfpm.*") )

#yum makecache
- name: yum makecache
  yum:
    update_cache: yes

#5.安装基础软件包
- name: Install base rpms packages
  yum:
    name: "{{ item }}"
    state: present
  loop:
      - net-tools
      - wget
      - tree
      - lrzsz
      - vim
      - unzip
      - httpd-tools
      - bash-completion
      - iftop
      - iotop
      - glances
      - ntp
      - ntpdate
      - rsync
      - rpcbind
      - nfs-utils
#6.创建web使用的系统用户www（UID、GID = 666）
- name: Create Group  "{{ web_group }}"
  group:
    name: "{{ web_group }}"
    gid: "{{ web_id }}"

- name: Create User "{{ web_user }}"
  user:
    name: "{{ web_user }}"
    uid: "{{ web_id }}"
    group: "{{ web_group }}"
    shell: /sbin/nologin
    create_home: yes

#7.调整文件描述符
- name: Add or modify nofile soft limit
  pam_limits:
    domain: '*'
    limit_type: "{{ item.limit_type }}"
    limit_item: "{{ item.limit_item }}"
    value: "{{ item.value }}"
  loop:
    - { limit_type: soft , limit_item: nofile , value: 100000 }
    - { limit_type: hard , limit_item: nofile , value: 100000 }


#.创建默认目录
- name: create base dirs /scripts and '/{{ rsync_backup }}' for all host
  file:
    path: "{{ item.path }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
    state: directory
    recurse: yes
  loop:
    - { path: /scripts, owner: root, group: root, mode: '0755' }
    - { path: '/{{ rsync_backup }}', owner: '{{ web_user }}', group: '{{ web_group }}', mode: '0755' }


#8.为每台节点添加备份脚本
- name: Copy Backup Scripts File 
  template:
    src: client_push_data_server.sh.j2
    dest: /scripts/client_push_data_server.sh
    mode: '0755'

#add rsync.passwd file
- name: Copy rsync.passwd File
  template:
    src: rsync.passwd.j2
    dest: /etc/rsync.passwd
    mode: '0600'


#9.定时执行该脚本
- name: Configure crond backup
  cron:
    name: "This is Backup Scripts File"
    minute: "00"
    hour: "01"
    job: "sh /scripts/client_push_data_server.sh &>/dev/null"

##.定时同步时间从aliyun
#- name: sync date from aliyun ntp
#  cron:
#    name: "sync date from aliyun ntp"
#    minute: "30"
#    hour: "00"
#    job: "ntpdate ntp.aliyun.com  &>/dev/null"
#
#使用ntpd服务同步主机时间,ntp.conf里使用if判断是否为manger主机，若是：使用服务端配置。
- name: copy ntp.conf and ntpd files to all hosts
  template:
    src: "{{item.src}}"
    dest: "{{item.dest}}"
    backup: yes
  loop:
    - { src: ntp.conf.j2, dest: /etc/ntp.conf }
    - { src: ntpd.j2, dest: /etc/sysconfig/ntpd }
  tags: ntp
- name: use ntpd service sync time from mangager-host
  systemd:
    name: ntpd
    state: restarted
    enabled: yes


#zabbix-agent安装
- name: yum install zabbix-agent
  yum:
    name: https://mirrors.aliyun.com/zabbix/zabbix/4.0/rhel/7/x86_64/zabbix-agent-4.0.21-1.el7.x86_64.rpm
    state: present

#拷贝zabbix_agentd.conf 文件
- name: copy zabbix_agentd.conf
  template:
    src: zabbix_agentd.conf.j2
    dest: /etc/zabbix/zabbix_agentd.conf
    

#启动zabbix-agent
- name: started and enabled zabbix-agent
  systemd:
    name: zabbix-agent
    state: restarted
    enabled: yes


