- name: Install Nginx Server
  yum:
    name: nginx
    state: present

- name: Configure Nginx Server
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  notify: Restart Nginx Server

- name: Remove Nginx Default.conf
  file:
    path: /etc/nginx/conf.d/default.conf
    state: absent


- name: Check Nginx Configure
  shell: nginx -t
  register: check_ngx
  changed_when:
    - false
    - check_ngx.stdout.find("successful")

- name: Started Nginx Server
  systemd:
    name: nginx
    state: started
