- name: Install Jdk Env For Tomcat
  yum:
    name: java
    state: present
- name: mkdir /tomcat for tomacat service
  file:
    path: /tomcat
    state: directory 
- name: Download Tomcat Web Server
  unarchive:
    src: "{{ tomcat_name }}.tar.gz"
    dest: /tomcat
- name: create soft link to /tomcat/tomcat 
  file:
    src: "/tomcat/{{ tomcat_name }}"
    dest: /tomcat/tomcat
    state: link

#配置tomcat缓存到redis中
- name: copy some .jar packages to lib/
  copy:
    src: "{{ item }}"
    dest: /tomcat/tomcat/lib
  loop:
    - commons-pool2-2.6.2.jar
    - jedis-3.0.1.jar
    - slf4j-api-1.7.26.jar
    - tomcat-cluster-redis-session-manager-4.0.jar
- name: copy redis-data-cache.properties to conf/
  template:
    src: redis-data-cache.properties.j2
    dest: /tomcat/tomcat/conf/redis-data-cache.properties

- name: copy context.xml to conf/
  copy:
    src: context.xml
    dest: /tomcat/tomcat/conf
#缓存配置完   

#拷贝启动脚本（使用www启动tomcat）
- name: cp tomcat-start as www sh file
  template:
    src: start-www.sh.j2
    dest: /tomcat/tomcat/bin/start-www.sh
    mode: '0750'
#拷贝关闭脚本（使用www关闭tomcat）
- name: cp tomcat-stop as www sh file
  template:
    src: stop-www.sh.j2
    dest: /tomcat/tomcat/bin/stop-www.sh
    mode: '0750'

#chown -R www.www /tomcat
- name: chown -R www. /tomcat
  file:
    path: /tomcat
    state: directory
    owner: www
    group: www
    mode: '0750'
    recurse: yes
#加入开机启动
#- name: enabled tomcat start host
  
 
- name: Started Tomcat Web Server
  shell: cd /tomcat/tomcat/bin &&
         nohup ./start-www.sh &
