
- name: unarchive " {{ wecenter }}" packages to  "{{ web_code }}"
  unarchive:
    src: "{{ wecenter }}.zip"
    dest: "{{ web_code }}"
    owner: "{{ web_user }}"
    group: "{{ web_group }}"



- name: add "{{ vhost_name2 }}" vhost to nginx
  template:
    src: "{{ vhost_name2 }}.conf.j2"
    dest: "/etc/nginx/conf.d/{{ vhost_name2 }}.conf"
  notify: Restart Nginx Server

#- name: mount "{{ vhost_name2 }}" static files to "{{ wecenter_dir }}"
#  mount:
#    src: "{{ nfs_vip }}:{{ wecenter_dir }}"
#    path: "{{ web_code }}/{{ wecenter }}/uploads"
#    opts: defaults
#    fstype: nfs
#    state: mounted
#  ignore_errors: yes
