
- name: unarchive " {{ wecenter }}" packages to  "{{ web_code }}"
  unarchive:
    src: "{{ wecenter }}.zip"
    dest: "{{ web_code }}"
    owner: "{{ web_user }}"
    group: "{{ web_group }}"



- name: add "{{ vhost_name2 }}" vhost to nginx
  template:
    src: zh.com.conf.j2
    dest: "/etc/nginx/conf.d/{{ vhost_name2 }}.conf"
  notify: Restart Nginx Server




#mount前启动rpcbind服务
- name: systemctl start and enable rpcbind
  systemd:
    name: rpcbind
    state: restarted
    enabled: yes

- name: mount "{{ vhost_name2 }}" static files to "{{ wecenter_dir }}"
  mount:
    src: "{{ nfs_vip }}:{{ wecenter_dir }}"
    path: "{{ web_code }}/{{ wecenter }}/wp-content"
    opts: defaults
    fstype: nfs
    state: mounted
  ignore_errors: yes
