- name: Restart Tomcat Service
  shell: cd /tomcat/tomcat/bin &&
         nohup ./stop-www.sh &&
         nohup ./start-www.sh &

- name: Restart Nginx Service
  systemd:
    name: nginx
    state: restarted

