####初始化系统IP和hostname
- name: setup static ip address
  template:
    src: eth0.j2
    dest: /etc/sysconfig/network-scripts/ifcfg-eth0

#- name: template dns
#  template:
#    src: resolv.conf.j2
#    dest: /etc/resolv.conf
   
- name: reset hostname
  hostname:
    name: "{{ hostname }}" 


- name: restart network
  systemd:
    name: network
    state: restarted

