####初始化系统IP和hostname
- name: copy hosts file
  copy:
    src: hosts
    dest: /etc/hosts
    backup: yes

#将所有主机的dhcp配置为静态内网ip，网卡为：eth0
- name: setup static ip address at "{{ eth0 }}"
  template:
    src: "{{ eth0 }}.j2"
    dest: "/etc/sysconfig/network-scripts/ifcfg-{{ eth0 }}"
    backup: yes

#- name: template dns
#  template:
#    src: resolv.conf.j2
#    dest: /etc/resolv.conf
   
- name: reset hostname
  hostname:
    name: "{{ hostname }}" 



- name: restart network
  systemd:
    name: network
    state: restarted

