- name: Install PHP-FPM Server
  yum:
    name: "{{ packages }}"
  vars:
    packages:
      - php71w
      - php71w-cli
      - php71w-common
      - php71w-devel
      - php71w-embedded
      - php71w-gd
      - php71w-mcrypt
      - php71w-mbstring
      - php71w-pdo
      - php71w-xml
      - php71w-fpm
      - php71w-mysqlnd
      - php71w-opcache
      - php71w-pecl-memcached
      - php71w-pecl-redis
      - php71w-pecl-mongodb

- name: Configure  php.ini AND php-fpm.d/www.conf
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  loop:
    - { src: php.ini.j2 , dest: /etc/php.ini }
    - { src: php_www.conf.j2 , dest: /etc/php-fpm.d/www.conf } 
  notify: Restart PHP-FPM Server

- name: Check PHP-FPM Server
  shell: php-fpm -t
  register: check_php_fpm
  changed_when:
    - false
    - check_php_fpm.stdout.find('successful')

- name: Started PHP-FPM Server
  systemd:
    name: php-fpm
    state: started




