- name: Install Mariadb Server
  yum:
    name: 
      - mariadb
      - mariadb-server
      - MySQL-python
    state: present

- name: Started Mariadb Server
  systemd:
    name: mariadb
    state: started
    enabled: yes

#mysql_db主要负责创建数据库（创建、导出、导入...）
- name: Create Application Database
  mysql_db:
#    login_user: root
#    login_password: 123456
    name: "{{ item }}"
    state: present
  loop:
    - phpmyadmin
    - zh
    - zrlog

- name: Allow User Access Database
  mysql_user:
#    login_user: root
#    login_password: 123456
    name: "{{ item.name }}"
    password: '{{ item.password }}'
    priv: '{{ item.priv }}'
    host: '{{ item.host }}'
    state: present
  loop:
    - { name: phpmyadmin, password: '123456', priv: '*.*:ALL', host: '172.16.1.%' }
    - { name: zh, password: '123456', priv: '*.*:ALL', host: '172.16.1.%' }
    - { name: zrlog, password: '123456', priv: '*.*:ALL', host: '172.16.1.%' }
